version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: hadeed4747/django_project_todo:latest
    ports:
      - "8000:8000"

    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=your_database_name
      - DJANGO_DB_USER=your_username
      - DJANGO_DB_PASSWORD=your_password

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
